apiVersion: v1
kind: Service
metadata:
  labels:
    akutan/app: akutan-api
    akutan/type: akutan-api
  name: akutan-api-http
  namespace: akutan-dev
spec:
  ports:
  - port: 9988
    name: http
  selector:
    akutan/app: akutan-api
  type: LoadBalancer
---
# this normally wouldn't need to be split into 2 separate services
# but minikube service doesn't know how to restict on a portName.
# So we have two services, such that you can then do
# minikube service -n akutan-dev akutan-api-http --url and get one
# this is correct.
apiVersion: v1
kind: Service
metadata:
  labels:
    akutan/app: akutan-api
    akutan/type: akutan-api
  name: akutan-api-grpc
  namespace: akutan-dev
spec:
  ports:
  - port: 9987
    name: grpc
  selector:
    akutan/app: akutan-api
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: akutan-api-config
  namespace: akutan-dev
data:
  config.json: |
    {{json "    " $.APICfg }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: akutan-api
  labels:
    akutan/app: akutan-api
    akutan/type: akutan-api
  namespace: akutan-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      akutan/app: akutan-api
  template:
    metadata:
      name: akutan-api
      labels:
        akutan/app: akutan-api
        akutan/type: akutan-api
    spec:
      containers:
      - name: akutan-api
        image: {{$.Images.API}}
        args: [ "-cfg", "/etc/akutan/config.json" ]
        ports:
        - containerPort: 9988
          name: http
        - containerPort: 9987
          name: grpc
        volumeMounts:
        - name: config-volume
          mountPath: /etc/akutan
      volumes:
        - name: config-volume
          configMap:
            name: akutan-api-config
