{{- range $i, $dv := .DiskViews}}
{{- if gt $i 0}}
---
{{- end}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$dv.Name}}-config
  namespace: akutan-dev
data:
  config.json: |
    {{json "    " $dv.Cfg }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{$dv.Name}}
  labels:
    akutan/app: {{$dv.Name}}
    akutan/type: akutan-view
  namespace: akutan-dev
  annotations:
    akutan/space: "{{$dv.Cfg.DiskView.Space}}"
    akutan/firstHash: "{{$dv.Cfg.DiskView.FirstHash}}"
    akutan/lastHash: "{{$dv.Cfg.DiskView.LastHash}}"
spec:
  containers:
  - name: akutan-diskview
    image: {{$.Images.DiskView}}
    args: [ "-cfg", "/etc/akutan/config.json" ]
    ports:
    - containerPort: 9980
      name: grpc
    volumeMounts:
    - name: data-volume
      mountPath: /db
    - name: config-volume
      mountPath: /etc/akutan
  volumes:
  - name: data-volume
{{- if $.UsePersistentVolumes }}
    persistentVolumeClaim:
      claimName: {{$dv.Volume.Claim}}
{{- else }}
    emptyDir: {}
{{- end }}
  - name: config-volume
    configMap:
      name: {{$dv.Name}}-config
{{- end}}
