apiVersion: v1
kind: Pod
metadata:
  name: kafka-log-1
  labels:
    akutan/app: kafka-log-1
    akutan/type: kafka
  namespace: akutan-dev
spec:
  containers:
  - name: kafka-log-1
    image: {{$.Images.LogService}}
    ports:
    - containerPort: 2181
      name: zookeeper
    - containerPort: 9092
      name: kafka
    volumeMounts:
    - name: kafka-log-1
      mountPath: /log
  volumes:
  - name: kafka-log-1
{{- if $.UsePersistentVolumes }}
    persistentVolumeClaim:
      claimName: log-store-1
{{- else }}
    emptyDir: {}
{{- end }}
