kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: akutan-dev
  name: resource-reader
rules:
  # "" indicates the core API group in which pods resides
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-reader
  namespace: akutan-dev
subjects:
  - kind: ServiceAccount
    name: default
    namespace: akutan-dev  
roleRef:
  kind: Role
  name: resource-reader
  apiGroup: rbac.authorization.k8s.io
