apiVersion: v1
kind: ConfigMap
metadata:
  name: akutan-txview-config
  namespace: akutan-dev
data:
  config.json: |
    {{json "    " $.TxViewCfg }}
---
apiVersion: v1
kind: Pod
metadata:
  name: akutan-txview
  labels:
    akutan/app: akutan-txview
    akutan/type: akutan-view
  namespace: akutan-dev
  annotations:
    akutan/features: "Diagnostics"
spec:
  containers:
  - name: akutan-txview
    image: {{$.Images.TxView}}
    args: [ "-cfg", "/etc/akutan/config.json" ]
    ports:
    - containerPort: 9980
      name: grpc
    volumeMounts:
    - name: config-volume
      mountPath: /etc/akutan
  volumes:
  - name: config-volume
    configMap:
      name: akutan-txview-config
